### ISSUE TITLE
问题反馈：设置针对dp2MServer的参数过程中报错

### ISSUE THREAD

**Issue by lunvo** [DigitalPlatform/chord#215]
通过 chordInstaller 安装完 dp2Capo 模块。
在配置实例的过程中，设置针对dp2MServer的参数，如下图。
<image src='https://user-images.githubusercontent.com/39716557/48456333-a2436980-e7f9-11e8-8ac0-6ff70ffb9833.png' width='480px'>

点 检测 或 确定 按钮时，弹出对话框：
<image src='https://user-images.githubusercontent.com/39716557/48456441-18e06700-e7fa-11e8-9458-7b2b833e7f1e.png' width='600px'>

**Comment by lunvo** [comment]
【开发老师留言2018/11/14 12:37:24】
刚才 dp2mserver 报错问题，是更新了 mongodb 驱动部分 nuget 包造成的。我不想退回原来的 nuget 包版本。然后花了半个多一个小时，把很多 string [] 改成 List<string> 以后，算是基本测试通过了。

**Comment by renyh** [comment]
已解决
