### ISSUE TITLE
问题反馈：任意用户可以查看非public图书馆的“好书推荐”。

### ISSUE THREAD

**Issue by lunvo** [DigitalPlatform/chord#217]
开发老师留言（2018/11/21 15:07:03）：
现在随便一个人就可以看XXXXX的“好书推荐”，还可以看到具体的书目信息。
记得原来的效果是，随便一个人进入他们的书目查询界面，会有红色的报错提示。这是正确的。而现在随便一个人可以进入这个书目查询界面。我觉得应该恢复以前的效果，就是连进入都不让进入。

XXXXX的微信公众号的 bug，注意看看是不是在各个环节都卡住了权限，如果这个站点不让 public 访问，各个环节都应该不允许单独访问。比如，如果好书推荐功能失守(意思是出现了 bug 导致允许 public 访问)，那再这里点击锚点去显示详细书目记录的时候，显示那个也不应该失守。应该是单独防范的。另外，如果允许 URL 单独访问一条书目记录，有这样的入口，也是应该卡住的，这应该从代码编写的各个环节检查一下。总的来说，就是不应该依赖单一一个入口来防范权限。所谓依赖单一入口，意思就是说在单一入口位置做了防范，但其他所有环节都毫无防范。这种单一入口防范是不行的。类似，C/S 模式中，不应该仅依靠前端防范(而是要服务器加以主动防范)。

**Comment by renyh** [comment]
已修复
