### ISSUE TITLE
如何配置微信公众号

### ISSUE THREAD

**Issue by lunvo** [DigitalPlatform/chord#222]
##  一、配置 dp2mserver 服务器参数

1. 通过Chord Installer创建一个dp2capo实例，创建方法参见文档：[dp2Capo 安装配置](https://github.com/DigitalPlatform/chord/wiki/dp2Capo-安装配置)

2. 配置dp2library服务器（L）参数时，除了创建capo代理账户外，还需要设置“消息队列”属性页
消息队列路径。一般是直接点“获得”按钮，自动从刚才配置的 dp2library 服务器获得这个消息队列路径。会弹出一个对话框要求输入 dp2library 服务器的管理员账户，一个较高权限的账户名和密码，使得安装程序可以获得这个消息队列路径，按提示操作即可。
注：这个属性页的参数，只是在需要配置 dp2mserver 服务器参数的情况下需要配置。

3. 配置 dp2mserver 服务器参数，在“设置针对dp2MServer的参数”页面，填写相关信息。
1）dp2MServer服务器URL（U）: 此项地址是默认的，不需要修改“http://dp2003.com:8083/dp2mserver”
2）创建一个dp2MServer账户（针对上述dp2MServer）
2.1）用户名的格式一般是“capo_***”，输入密码后点检测，若已存在就不需要再创建。
2.2）若用户名不存在，点创建，弹出“确认身份”页，输入dp2mserver 服务器的用户名和密码（由服务部门人员提供）-确认-弹出对话框中输入“图书馆名”-确认-弹出对话框“是否允许webCall（通过dp2Router访问dp2library）?”-点“是”，然后确定。

**Comment by maruimarui** [comment]
todo

**Comment by maruimarui** [comment]
todo

**Comment by maruimarui** [comment]
## 微信公众号增加分馆
以 数字平台 图书馆为例，假设内务创建了一个分馆：数字平台分馆。总馆配置了公众号，给分馆配置公众号的操作步骤如下：

1. 登录 dp2mserver 所在服务器。

2. 编辑位于 D:\weixin_data 路径下的 libcfg.xml 文件，在 数字平台 总馆对应的配置文件加一行，id保持一致，name和libraryCode输入对应的分馆名称，保存。

修改前
```
  <area name="数字平台公司">
    <lib id="576d38c1ea3bcbe360040667" name="数字平台" libraryCode="" />
  </area>
```
修改后：
```
  <area name="数字平台公司">
    <lib id="576d38c1ea3bcbe360040667" name="数字平台" libraryCode="" />
    <lib id="576d38c1ea3bcbe360040667" name="数字平台分馆" libraryCode="数字平台分馆" />
  </area>
```
注意：总馆和分馆共用一个图书馆id

3. 打开IIS管理器，回收 ilovelibrary 应用池，使修改生效。
<img width="720" alt="image" src="https://user-images.githubusercontent.com/39716557/51017037-8405aa00-15ad-11e9-84da-2a331bd3cd9f.png">
4. 查看微信公众号，分馆已经显示在列表中。
<img width="960" alt="image" src="https://user-images.githubusercontent.com/39716557/51017009-69333580-15ad-11e9-8e48-86e62234e802.png">

**Comment by renyh** [comment]
已迁至wiki，并且在wiki里更新了文字 ，这个issue作废。
