### ISSUE TITLE
书目录中检索途径选择作者检索结果的说明

### ISSUE THREAD

**Issue by liuzhenliuzhen** [DigitalPlatform/chord#225]

**Comment by liuzhenliuzhen** [comment]
1.点击 常用窗口/书目录查询 ，检索途径选择责任者，输入检索内容，检索结果可能出现未命中。
原因：
责任者在MARC记录里对应的配置号为7开头$a字段，书目查询窗的下方的浏览格式配置作者这一列配置号抽取的是200$a字段，查询只输入作者检索词不一定能检索到。

**Comment by renyh** [comment]
已移至dp2常见问题
