### ISSUE TITLE
我爱图书馆 公众号新增读者登记报错

### ISSUE THREAD

**Issue by liuzhenliuzhen** [DigitalPlatform/chord#233]
### 测试目的

在 我爱图书馆 公众号，绑定的工作人员为活动账号时，工作人员增读者登记或者修改保存读者是否正常

### 测试准备

1. 在dp2内务用超级管理员登录，新增图书馆工作人员用户，配置图书馆工作人员的相应管理权限。

2. 在公众号绑定工作人员账户。

### 操作步骤

1. 在 我爱图书馆 公众号，绑定的工作人员为活动账号。

2. 点击菜单 更多/读者登记，进入读者登记界面，编辑 证条码号、读者类别，姓名、性别、单位、手机号、目标读者库。点击 新增 按钮，提示报错信息：图书馆 测试服务器 的桥接服务器失去连接，无法访问，点击 OK，关闭提示框。

3. 用工作人员账户登录内务，在 读者窗 新增读者记录，可 新增 成功。

4. 在读者登记界面，输入证条码号，点击 装载 按钮，读者信息加载到界面，编辑修改读者信息，点击 保存 按钮，提示报错信息：图书馆 测试服务器 的桥接服务器失去连接，无法访问，点击 OK，关闭提示框。

5. 用工作人员账户登录内务，在 读者窗 加载一个读者记录修改读者信息，可 保存 成功。

### 测试结果

20190606-10:00-liuzhen:测试与预期不一致，若一个工作人员账户在内务可以新增和修改读者记录，在公众号也可以操作。

2020/1/21 是由于dp2mserver帐户缺setReaderInfo权限

**Comment by renyh** [comment]
上述问题由于dp2mserver帐户缺setReaderInfo权限，已将报错改的更准确一些。
